# Creates a docker container being hosted on port 5000
version: '3.4'

services:
    device-registry:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - 5000:80